### ISSUE TITLE
An Error Occured!

### ISSUE THREAD

**Issue by davidpasini** [Zaczero/CBBI#4]
Hi Kamil,

Is this a LIB issue? Last week the script was running with no hiccups. I have just tried to run main.py and it keeps retrying but returning always these lines.

:: Retrying in 10 seconds...
Fetching daily Google Trends: 100%|███████████████████████████████████████████████████| 57/57 [00:00<00:00, 211.09it/s]
Error: An error occurred!
Traceback (most recent call last):
  File "D:\OneDrive\Work (Current)\ValueUnbanking\CBBI-main\main.py", line 146, in run_and_retry
    run(json_file, charts_file)
  File "D:\OneDrive\Work (Current)\ValueUnbanking\CBBI-main\main.py", line 78, in run
    df_bitcoin[metric.name] = metric.calculate(df_bitcoin_org.copy(), ax)
  File "D:\OneDrive\Work (Current)\ValueUnbanking\CBBI-main\metrics\rhodl_ratio.py", line 60, in calculate
    df = df.merge(_fetch_df(), on='Date', how='left')
  File "D:\OneDrive\Work (Current)\ValueUnbanking\CBBI-main\metrics\rhodl_ratio.py", line 36, in _fetch_df
    response.raise_for_status()
  File "C:\Python39\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://www.lookintobitcoin.com/django_plotly_dash/app/rhodl_ratio/_dash-update-component

**Comment by Zaczero** [comment]
> Is this a LIB issue?

Yes, try again later. Happens sometimes.

![image](https://user-images.githubusercontent.com/10835147/139658722-af1b9d4c-eb61-4779-84dd-d99e9fdc3bb9.png)

**Comment by Zaczero** [comment]
I implemented a small fallback function in 3d55e9e6247e349985ec2af837d7a5e35831a5a5 not to stall other metric updates.

**Comment by davidpasini** [comment]
Working like a charm now! Tnx for the amazing work Kamil! :D
